apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-a
  description: Team A responsible for gRPC APIs
spec:
  type: team
  profile:
    displayName: Team A
    email: team-a@example.com
  children: [cindy, joel]
---

apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: cindy
  description: Personal developer group for Cindy
spec:
  type: group
  profile:
    displayName: Cindy
    email: cindy@example.com
  parent: team-a

---

apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: joel
spec:
  profile:
    displayName: Joel
    email: joel@example.com
  memberOf: [team-a]