apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: example-apis
  description: A collection of all Backstage example APIs
spec:
  targets:
    - ./apis/cindys-api.yaml
    - ./apis/hello-world-api-new.yaml